# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkepFPhxcKwccsIHUtL_X48-4nW11PE9
"""

# document_classifier.py

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix
)
import joblib

# ─────────────────────────────────────────
# 1. LOAD DATASET
# ─────────────────────────────────────────
# Using 4 categories for a clean, focused demo
# First, let's get all available category names to correct the list
print("Fetching all 20 Newsgroups categories...")
all_data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
print(f"Available categories: {all_data.target_names}")
print("\nPlease update the 'categories' list with valid names from above.\n")

# Corrected categories (example, you might need to adjust based on the printed list)
categories = ['sci.electronics', 'rec.sport.hockey', 'talk.politics.guns', 'comp.graphics'] # Assuming 'sci.electronics' is the correct one for 'sci.tech'

print("Loading dataset with selected categories...")
data = fetch_20newsgroups(subset='all', categories=categories,
                          remove=('headers', 'footers', 'quotes'))

X = data.data      # list of raw text strings
y = data.target    # integer labels
label_names = data.target_names

print(f"Total samples: {len(X)}")
print(f"Categories: {label_names}")

# ─────────────────────────────────────────
# 2. SPLIT DATA
# ─────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTrain size: {len(X_train)}, Test size: {len(X_test)}")

# ─────────────────────────────────────────
# 3. FEATURE EXTRACTION — TF-IDF
# ─────────────────────────────────────────
# TF-IDF converts raw text into numerical features
vectorizer = TfidfVectorizer(
    max_features=10000,   # top 10k most important words
    stop_words='english', # remove common words like "the", "is"
    ngram_range=(1, 2)    # use both single words and word pairs
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf  = vectorizer.transform(X_test)

print(f"\nFeature matrix shape: {X_train_tfidf.shape}")

# ─────────────────────────────────────────
# 4. TRAIN MODEL
# ─────────────────────────────────────────
print("\nTraining Logistic Regression...")
model = LogisticRegression(max_iter=1000, C=5.0, solver='lbfgs', multi_class='auto')
model.fit(X_train_tfidf, y_train)

# ─────────────────────────────────────────
# 5. EVALUATE
# ─────────────────────────────────────────
y_pred = model.predict(X_test_tfidf)

print(f"\n✅ Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_names))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_names, yticklabels=label_names)
plt.title('Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('confusion_matrix.png')
plt.show()
print("Confusion matrix saved as confusion_matrix.png")

# ─────────────────────────────────────────
# 6. SAVE MODEL
# ─────────────────────────────────────────
joblib.dump(model, 'model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')
print("\nModel and vectorizer saved!")

# ─────────────────────────────────────────
# 7. PREDICTION FUNCTION
# ─────────────────────────────────────────
def predict_document(text):
    """Predict the category of a new document."""
    vec = joblib.load('vectorizer.pkl')
    clf = joblib.load('model.pkl')
    features = vec.transform([text])
    pred = clf.predict(features)[0]
    prob = clf.predict_proba(features)[0]
    return {
        "predicted_category": label_names[pred],
        "confidence": f"{max(prob)*100:.1f}%"
    }

# Test it!
sample = "The graphics card rendering pipeline uses OpenGL shaders."
result = predict_document(sample)
print(f"\nSample prediction: {result}")